FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y \
  libpq-dev \
  wget \
  curl \
  unzip \
  gnupg2 \
  curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update -qq \
  && apt-get install -y google-chrome-stable \
  CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
  wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P /tmp/ && \
  unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/ && \
  rm /tmp/chromedriver_linux64.zip \
  gem install bundler

WORKDIR /app

COPY . /app

RUN bundle install

ENV RACK_ENV=test

CMD ["/bin/bash"]