version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rebase_labs
      POSTGRES_PASSWORD: labs_123
      POSTGRES_DB: labs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: test_123
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
