version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rebase_labs
      POSTGRES_PASSWORD: labs_123
      POSTGRES_DB: labs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: test_123
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://rebase_labs:labs_123@db:5432/labs_db

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test_runner
    volumes:
      - .:/app
    depends_on:
      - db_test
    environment:
      DATABASE_URL: postgres://tester:test_123@db_test:5432/test_db
    tty: true
    stdin_open: true
    profiles:
      - test

  cypress_test:
    build:
      context: .
      dockerfile: Dockerfile.test_runner_js
    volumes:
      - .:/app
    depends_on:
      - app
    environment:
      DATABASE_URL: postgres://tester:test_123@db_test:5432/test_db
      CYPRESS_baseUrl: http://app:3000
    tty: true
    stdin_open: true
    profiles:
      - test

volumes:
  postgres_data:
