FROM ruby:3.2.2

COPY Gemfile Gemfile.lock ./

RUN apt-get update -qq && apt-get install -y libpq-dev && gem install bundler && bundle install

WORKDIR /app

COPY . /app

ENV RACK_ENV=test

CMD ["/bin/bash"]